// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofjzlwynchwwnbzlkced.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9manpsd3luY2h3d25iemxrY2VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MDY3MTUsImV4cCI6MjA1MDE4MjcxNX0.7_spp6k2f7u6KDFDuqcodu2Cje-VnFbKN6pBKJQ-YYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);